#!/usr/bin/env bash
# VibePlay — one-command deploy for a free single VM (Oracle Cloud Always Free, ARM/x86).
#
# Run from the repo root on the VM:
#   git clone https://github.com/MaksMykolenko/VibePlay.git
#   cd VibePlay
#   ./deploy-oracle.sh
#
# Idempotent: re-running keeps your generated secrets (.env) and just rebuilds.
set -euo pipefail

cd "$(dirname "$0")"
echo "==> VibePlay deploy starting in $(pwd)"

# ---------------------------------------------------------------------------
# 1) Docker + compose plugin
# ---------------------------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  echo "==> Installing Docker..."
  curl -fsSL https://get.docker.com | sudo sh
  sudo usermod -aG docker "$USER" || true
fi
DC="docker compose"
if ! docker compose version >/dev/null 2>&1; then DC="docker-compose"; fi
# Use sudo for docker if the current user isn't yet in the docker group this session.
SUDO=""
if ! docker info >/dev/null 2>&1; then SUDO="sudo"; fi

# ---------------------------------------------------------------------------
# 2) Public IP (used for the link + game wildcard via sslip.io)
# ---------------------------------------------------------------------------
IP="$(curl -fsS https://api.ipify.org || curl -fsS https://ifconfig.me || true)"
if [[ -z "${IP}" ]]; then
  echo "Could not auto-detect the public IP. Set it manually:  IP=1.2.3.4 ./deploy-oracle.sh" >&2
  IP="${IP:-}"
fi
[[ -n "${IP:-}" ]] || { echo "No IP — aborting."; exit 1; }
echo "==> Public IP: ${IP}"

# ---------------------------------------------------------------------------
# 3) .env — generate once, then reuse (stable secrets across re-runs)
# ---------------------------------------------------------------------------
if [[ ! -f .env ]]; then
  echo "==> Generating .env (secrets + origins)..."
  gen() { openssl rand -hex "$1"; }
  cat > .env <<EOF
# Generated by deploy-oracle.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Keep secret.
SESSION_SECRET=$(gen 64)
PASSWORD_PEPPER=$(gen 32)
PREVIEW_URL_SECRET=$(gen 32)
POSTGRES_PASSWORD=$(gen 24)
MINIO_ROOT_USER=vibeplay
MINIO_ROOT_PASSWORD=$(gen 24)

# App is served over plain HTTP on this VM (no domain/TLS).
# Visit WEB_ORIGIN in your browser. The game host uses sslip.io so every
# published version gets its own subdomain that resolves to this IP for free.
WEB_ORIGIN=http://${IP}.sslip.io
GAME_ORIGIN=http://games.${IP}.sslip.io:8080
GAME_FRAME_SRC=http://*.games.${IP}.sslip.io:8080
S3_PUBLIC_ENDPOINT=http://${IP}.sslip.io:9000

INVITE_ONLY=true
EOF
  chmod 600 .env
else
  echo "==> Reusing existing .env"
fi

# ---------------------------------------------------------------------------
# 4) Open the host firewall (Oracle's Ubuntu image blocks inbound by default).
#    NOTE: you must ALSO add ingress rules for 80, 8080, 9000 in the Oracle
#    console (VCN → Security List). This only handles the in-VM iptables.
# ---------------------------------------------------------------------------
open_port() {
  local p="$1"
  if ! sudo iptables -C INPUT -p tcp --dport "$p" -j ACCEPT 2>/dev/null; then
    sudo iptables -I INPUT 1 -p tcp --dport "$p" -j ACCEPT
    echo "   opened tcp/$p"
  fi
}
if command -v iptables >/dev/null 2>&1; then
  echo "==> Opening host firewall for 80, 8080, 9000..."
  open_port 80; open_port 8080; open_port 9000
  sudo netfilter-persistent save 2>/dev/null || sudo sh -c 'iptables-save > /etc/iptables/rules.v4' 2>/dev/null || true
fi

# ---------------------------------------------------------------------------
# 5) Build + start the stack
# ---------------------------------------------------------------------------
echo "==> Building and starting the stack (first build takes several minutes)..."
$SUDO $DC -f docker-compose.oracle.yml --env-file .env up -d --build

echo ""
echo "============================================================"
echo "  VibePlay is starting up."
echo ""
echo "  App:        http://${IP}.sslip.io"
echo "  Game host:  http://games.${IP}.sslip.io:8080"
echo "  Mail (UI):  (internal — Mailpit; not exposed)"
echo ""
echo "  Watch logs:     $SUDO $DC -f docker-compose.oracle.yml logs -f"
echo "  Service status: $SUDO $DC -f docker-compose.oracle.yml ps"
echo ""
echo "  NEXT — create your first admin login, then ./admin-bootstrap.sh prints it:"
echo "    ./admin-bootstrap.sh 'YourStrongPassw0rd!'"
echo "  Then log in at  http://${IP}.sslip.io  with  admin@vibeplay.local"
echo "  (From the admin panel you can generate invite links for real users.)"
echo "============================================================"
